from setuptools import setup

setup(name='FACTS.lab',
      version='0.1dev0',
      description='Python code generated by FACTS.lab members',
      url='https://github.com/factslab/code/python/',
      author='Aaron Steven White',
      author_email='aaron.white@rochester.edu',
      license='MIT',
      packages=['factslab', 'factslab.pytorch'],
      install_requires=['numpy',
                        'scipy',
                        'pandas',
                        'torch',
                        'patsy'],
      test_suite='nose.collector',
      tests_require=['nose'],
      zip_safe=False)
